import Character from './character';
import MagicAttack from './magic_attack';
import Team from './team';
import Bowman from './bowman';
import Daemon from './daemon';
import Magician from './magician';
import Swordsman from './swordsman';
import Undead from './undead';
import Zombie from './zombie';